### ISSUE TITLE
There is no ES7, etc

### ISSUE THREAD

**Issue by stevenvachon** [daumann/ECMAScript-new-features-list#6]
They stopped using that naming convention. It's best not to perpetuate thinking that it continues.

**Comment by PachVerb** [comment]
> They stopped using that naming convention. It's best not to perpetuate thinking that it continues.

hello！, you mean to come out in the official version, it is best not to use it in development?

**Comment by stevenvachon** [comment]
"ES6" was the original name for ES2015, and they kept it as a secondary/alternative name. ES2016 does not include "ES7", an onward to ES2019.

**Comment by PachVerb** [comment]
> "ES6" was the original name for ES2015, and they kept it as a secondary/alternative name. ES2016 does not include "ES7", an onward to ES2019.

Thank you for your relply.Why?  ES2016 does not include ES7.  Should it be just a name?

**Comment by stevenvachon** [comment]
I don't know why, but the committee decided that using a year as the version was better. Perhaps because it's easier to track the age/currency of each specification.

**Comment by PachVerb** [comment]
> I don't know why, but the committee decided that using a year as the version was better. Perhaps because it's easier to track the age/currency of each specification.

OK，i understand. thank you

**Comment by daumann** [comment]
I now replaced most ES7+ mentions, I kept a "ES7" in the title just so people who are looking with the keyword ES7 will find it.
Please call out any other naming changes you think should be changed.
