### ISSUE TITLE
Translate this repo to pt_BR

### ISSUE THREAD

**Issue by nandomoreirame** [daumann/ECMAScript-new-features-list#9]
I want to translate, can I?

what would be the right way to do it?

@daumann suggest something?

🥇

**Comment by daumann** [comment]
Hi @nandomoreirame I would suggest forking the repo so that you are in full control of when to update and what to translate.
Alternatively we could create PT branch for you to PR against.

**Comment by nandomoreirame** [comment]
I'll fork then
thanks @daumann 🤝

**Comment by daumann** [comment]
:+1:
